"""initial migration

Revision ID: e6312ed6a2a2
Revises: 
Create Date: 2020-10-01 17:04:22.377152

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e6312ed6a2a2"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pecha",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("secret_key", sa.String(length=32), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=255), nullable=True),
        sa.Column("pecha_id", sa.String(length=7), nullable=True),
        sa.Column(
            "role",
            sa.Enum("admin", "owner", "contributor", name="roletype"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    op.drop_table("pecha")
    # ### end Alembic commands ###
